image: node:22-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - cd server
    - npm install

test:
  stage: test
  tags:
    - docker
  privileged: true # allow DinD container to start a Docker daemon
  services:
    - docker:dind
    - name: mongo:latest
      alias: mongo
  variables:
    MONGODB_URI: "mongodb://mongo:27017/serverTestDB"
    DOCKER_TLS_CERTDIR: "" # Disable Docker TLS. Needed so docker CLI can talk to daemon
  script:
    - apk add --no-cache docker-cli
    - cd server
    - npm run build-docker
    - npm run ci-test


deploy:
  stage: deploy
  tags:
    - docker
  image: ruby:alpine
  script:
    - apk update && apk add git curl
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://$HEROKU_APP_NAME.herokuapp.com/
  only:
    refs:
      - master
    variables:
      - $HEROKU_APP_NAME
      - $HEROKU_API_KEY
